# -*- mode: ruby -*-
# vi: set ft=ruby :


RAM = 4096
CPU = 2
IP = "10.0.0.10"

Vagrant.configure("2") do |config|
    config.vm.define "minikube" do |minikube|
      minikube.vm.box = "geerlingguy/centos7"
      minikube.vm.network "private_network", type: "dhcp", ip: IP
      minikube.vm.synced_folder "mnt/", "/home/vagrant/synced_folder/"
      minikube.vm.hostname = "minikube"
      minikube.vm.provider "virtualbox" do |v|
        v.name = "minikube"
        v.memory = 4096
        v.cpus = 2
      end
      minikube.vm.provision :shell do |shell|
        shell.path = "install_minikube.sh"
      end
    end
  end

  